### ISSUE TITLE
Update Symfony from 3.4 to 4.4

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2824]
4.4 was just released by symfony and is a LTS release. We need to update from 3.4 to 4.4 (this is brought in via composer). A quick trial gave white screen of death on login screen with following error: 
```
The &quot;event_dispatcher&quot; service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.#0 /var/www/localhost/htdocs/openemr/vendor/symfony/dependency-injection/Container.php(225): Symfony\\Component\\DependencyInjection\\Container-&gt;make(&#039;event_dispatche...&#039;, 1)\n#1 /var/www/localhost/htdocs/openemr/vendor/symfony/dependency-injection/ContainerBuilder.php(555): Symfony\\Component\\DependencyInjection\\Container-&gt;get(&#039;event_dispatche...&#039;)\n#2 /var/www/localhost/htdocs/openemr/src/Core/Kernel.php(99): Symfony\\Component\\DependencyInjection\\ContainerBuilder-&gt;get(&#039;event_dispatche...&#039;)\n#3 /var/www/localhost/htdocs/openemr/src/Core/ModulesApplication.php(48): OpenEMR\\Core\\Kernel-&gt;getEventDispatcher()\n#4 /var/www/localhost/htdocs/openemr/interface/globals.php(582): OpenEMR\\Core\\ModulesApplication-&gt;__construct(Object(OpenEMR\\Core\\Kernel), &#039;/var/www/localh...&#039;, &#039;interface/modul...&#039;, &#039;zend_modules&#039;)\n#5 /var/www/localhost/htdocs/openemr/interface/login/login.php(25): require_once(&#039;/var/www/localh...&#039;)\n#6 {main}, referer: http://localhost:8082/setup.php?site=default
```

**Comment by zerai** [comment]
You should solve this problem if you mark services as public services change the definition of services
in the config / sevices.yml file
```
services:
    sample_subscriber:
        class: OpenEMR\Sample\Event\SampleSubscriber
        tags:
            - { name: kernel.event_subscriber }
        public: true
    admin.admin_menu_builder:
        class: OpenEMR\Admin\Service\AdminMenuBuilder
        arguments: ['@event_dispatcher']
        public: true
    calendar.event_subscriber:
        class: OpenEMR\Calendar\EventListener\CalendarSubscriber
        tags:
            - { name: kernel.event_subscriber }
        public: true
```
