### ISSUE TITLE
running easy docker while vpn'ing

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#4318]
### Describe the problem
```
Creating network "development-easy_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
````

### Describe the solution you'd like

add network to `docker-compose.yml`

```
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
```
